clone:
  default:
    image: plugins/git
    recursive: true
    group: clone
    submodule_update_remote: true
    submodule_override:
       docs-theme: https://github.com/PressLabs/docs-theme.git

  presslabs-org:
    image: alpine/git
    group: clone
    commands:
      # write the ssh key to disk
      - mkdir /root/.ssh
      - echo -n "$GIT_PUSH_SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      # add github to known hosts
      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      # clone presslabs-org
      - git clone git@github.com:/PressLabs/presslabs-org.git@prod /drone/src/presslabs-org
    secrets:
      - GIT_PUSH_SSH_KEY

pipeline:
  test:
    image: ubuntu:trusty
    group: build
    privileged: true
    environment:
      - PIP_DOWNLOAD_CACHE=/tmp/pip_download_cache
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - apt-get update && apt-get install -qy build-essential python-pip python-virtualenv python-dev software-properties-common python-software-properties libfuse-dev fuse git libffi-dev python3.4-dev
      - sudo add-apt-repository -y ppa:presslabs/gitfs
      - sudo apt-get update
      - sudo apt-get install -y libgit2 libgit2-dev
      - sudo chmod 660 /dev/fuse
      - echo user_allow_other | sudo tee -a /etc/fuse.conf > /dev/null
      - sudo chmod 644 /etc/fuse.conf
      - git config --global user.email "drone@example.com"
      - git config --global user.name "Drone CI"
      - make test
    volumes:
      - /var/cache/apt/:/var/cache/apt/
    when:
      branch: master

  build-docs:
    image: jobandtalent/mkdocs
    group: build
    commands:
      - cd docs/
      - mkdocs build --clean
      - for i in $(ls | grep -v compiled_docs); do rm -rf $i; done
      - mkdir -p /drone/src/presslabs-org/wp-content/root/gitfs
      - mv compiled_docs/* /drone/src/presslabs-org/wp-content/root/gitfs
      - rm -rf compiled_docs/
    when:
      branch: master

  update-presslabs-org:
    image: appleboy/drone-git-push
    branch: prod
    group: docs
    commit: true
    path: /drone/src/presslabs-org
    commit_message: "[docs] Update gitfs docs"
    remote: git@github.com:/Presslabs/presslabs-org.git
    secrets:
      - GIT_PUSH_SSH_KEY
    when:
      branch: master

workspace:
   base: /drone
   path: src/gitfs
