image: bradrydzewski / python
env:
    - PIP_DOWNLOAD_CACHE=/tmp/pip_download_cache
script:
    - sudo chown ubuntu:ubuntu /tmp/pip_download_cache
    - make drone
    - make test
    - coveralls
publish:
    pypi:
        username: presslabs
        password: {{ pypi_password }}
cache:
    - /var/cache/apt/
    - /tmp/pip_download_cache
