pipeline:
  test:
    image: ubuntu:18.04
    group: build
    privileged: true
    environment:
      - PIP_DOWNLOAD_CACHE=/tmp/pip_download_cache
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - apt-get update && apt-get install -qy build-essential python-pip python-virtualenv python-dev software-properties-common libfuse-dev fuse git libffi-dev python3.7-dev libgit2-dev
      - chmod 660 /dev/fuse
      - echo user_allow_other | tee -a /etc/fuse.conf > /dev/null
      - chmod 644 /etc/fuse.conf
      - git config --global user.email "drone@example.com"
      - git config --global user.name "Drone CI"
      - make test
    volumes:
      - /var/cache/apt/:/var/cache/apt/

  trigger-docs-build:
    image: plugins/downstream
    server: https://drone.presslabs.net
    fork: true
    secrets: [DRONE_TOKEN]
    repositories:
      - presslabs/docs
    when:
      branch: master
      event: push
