language: python
install:
    - sudo apt-get install -y software-properties-common python-software-properties
    - sudo add-apt-repository -y ppa:presslabs/testing-ppa
    - sudo apt-get update
    - sudo apt-get install -y libgit2-0 libgit2-dev git git-core
python:
  - "2.7"
  - "pypy"
script:
    - make test
